### PR TITLE
Add algorithm include in triangulator.h

### PR DESCRIPTION
**Pull request by kylebarron**
Ref #16, https://github.com/conda-forge/pydelatin-feedstock/pull/3

cc @davidbrochart

### CODE REVIEW

**Comment by kylebarron** [comment]
@davidbrochart You think I should make a new patch release now?

**Comment by davidbrochart** [comment]
Please wait, I'm trying out in https://github.com/conda-forge/pydelatin-feedstock/pull/3 by patching the files.

**Comment by davidbrochart** [comment]
You can remove the include in `triangulator.cpp`.

**Comment by davidbrochart** [comment]
OK so it still doesn't work, I think I need to patch directly in https://github.com/conda-forge/cpp-hmm-feedstock instead.

**Comment by davidbrochart** [comment]
Ah but pydelatin vendors `hmm` anyway, so it's useless.
Well, maybe you can make a release then :smile:

**Comment by kylebarron** [comment]
So do I need to make a change? If so can you just make a PR with the change?

**Pull request merged**
