### PR TITLE
Try to fix macOS wheel build

### PR DESCRIPTION
**Pull request by pypae**
Follow up of https://github.com/kylebarron/pydelatin/pull/37. 

Note: Somehow I can't run the workflows locally anymore, so this is kind of a shot in the dark. 

- Try to add `glm` to the path. I needed to do that locally, so this might also work on the runner.
- Use `macos-13` instead of `macos-latest`, because `macos-latest` uses M1 processors and I'm not sure if x86 wheels can be built.

### CODE REVIEW

**Comment by kylebarron** [comment]
Can you temporarily set the yaml to
```
# Only run on new tags starting with `v`
on:
  push:
```
so that we can test the wheel building on this branch?

**Comment by kylebarron** [comment]
I guess since I don't check for a tag, you should also comment out the release part while testing on this branch

**Comment by kylebarron** [comment]
I'm not sure why but the wheels aren't building on CI in this PR. Are the actions running on your fork?

**Comment by pypae** [comment]
Yes they are running [here](https://github.com/pypae/pydelatin/actions/runs/10560666995) 👍

**Comment by pypae** [comment]
The build seems to be successful, so I reverted the temporary changes.

**Comment by kylebarron** [comment]
Ok, I force pushed the v0.2.8 tag again, so wheels are attempting to build from main now

**Comment by kylebarron** [comment]
Looks like 0.2.8 is on pypi: https://pypi.org/project/pydelatin/0.2.8/#files

Can you try that out?

**Comment by pypae** [comment]
Works great, thank you!

```
pip install --no-cache pydelatin
Collecting pydelatin
  Downloading pydelatin-0.2.8-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.9 kB)
Requirement already satisfied: numpy in /Users/patrick/Library/Application Support/hatch/env/virtual/off-grid/iGlVZ8gk/off-grid/lib/python3.12/site-packages (from pydelatin) (2.1.0)
Downloading pydelatin-0.2.8-cp312-cp312-macosx_11_0_arm64.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.0/171.0 kB 4.1 MB/s eta 0:00:00
Installing collected packages: pydelatin
Successfully installed pydelatin-0.2.8
```

**Pull request merged**
