### PR TITLE
Switch order of `include`s

### PR DESCRIPTION
**Pull request by kylebarron**
cc @davidbrochart

This should fix it?

Ref https://github.com/conda-forge/pydelatin-feedstock/pull/3

### CODE REVIEW

**Comment by davidbrochart** [comment]
Let's try!

**Comment by kylebarron** [comment]
I don't have access to a windows machine locally... should I publish a new release with this?

**Comment by kylebarron** [comment]
I think https://stackoverflow.com/a/14243688/7319250 argues against this change?

**Comment by davidbrochart** [comment]
Yes but `glm` is header-only, so I'm not sure it holds.
Let me try patching the recipe before releasing.

**Comment by kylebarron** [comment]
It would be nice to test it in some way before releasing a new version to pypi

**Comment by davidbrochart** [comment]
Ah but you included `<algorithm>` in `triangulator.cpp`, you should do it in `triangulator.h` (and before `glm.hpp`). So I guess that deserves a release anyway.

**Comment by kylebarron** [comment]
Ah so this PR probably doesn't matter at all, I just need to add the include to `triangulator.h`?

**Comment by davidbrochart** [comment]
Yes

**Pull request merged**
